spring:
  application:
    name: shop-database
cache:
  redis:
    expiration: 3600 # By default, objects stay 1 hour (in seconds) in the cache
    server: redis://localhost:6379
    cluster: false
    # server: redis://localhost:6379,redis://localhost:16379,redis://localhost:26379
    # cluster: true